<Project Sdk="Microsoft.NET.Sdk">
 <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0-windows</TargetFramework><UseWPF>true</UseWPF><ApplicationManifest>../../src/Winora/app.manifest</ApplicationManifest></PropertyGroup>
 <ItemGroup><ProjectReference Include="../../src/Winora/Winora.csproj" /></ItemGroup>
</Project>
